### ISSUE TITLE
Include GPL text as well as LGPL

### ISSUE THREAD

**Issue by sanxiyn** [withoutboats/Chekhov#2]
Please read [How to use GNU licenses for your own software](http://www.gnu.org/licenses/gpl-howto.html).

> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs the license is usually in a file called COPYING.
> If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights.

Since LGPLv3 is worded as an addition to GPLv3, you should distribute both GPLv3 and LGPLv3. Distributing LGPLv3 alone does not make sense.

**Comment by withoutboats** [comment]
Thanks! I just curl'd the text of the LGPL without reading the instructions clearly.
